services:
  terraform:
    build:
      context: .
      dockerfile: infra/Dockerfile
    environment:
      - TF_LOG=INFO
    volumes:
      - ./:/app
      - ~/.aws:/root/.aws:ro
    working_dir: /app
    networks:
      - backend
    entrypoint: [ "/bin/bash", "-c" ]
    command: >
      "terraform -chdir=infra apply --auto-approve &&
      ./generate-env.sh"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./api/v1/.env
        target: /app/v1/.env
        read_only: true
      - ~/.aws:/root/.aws:ro
      - ./api/v1/static:/app/v1/static
      - ./api/v1/templates:/app/v1/templates
    depends_on:
      terraform:
        condition: service_completed_successfully
        required: true
    networks:
      - backend

networks:
  backend:
    driver: bridge
