version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - api/v1/.env_file
    depends_on:
      - terraform
  
  terraform:
    build:
      context: .
      dockerfile: infra.Dockerfile
    env_file:
      - .env
    volumes:
      - ./infra:/terraform
      - ./api/v1/.env:/terraform/.env
