name: CI/CD Pipeline

'on':
  push:
    branches:
      - remmy
  pull_request:
    branches:
      - remmy

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Terraform init and Apply
        run: |
          cd infra
          terraform init
          terraform plan
          terraform apply --auto-approve
          cd ..
          ./generate-env.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build API Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/file-sharing-api:latest -f api/Dockerfile .

      - name: Run API Tests
        run: |
          docker run --rm \
            -v $(pwd)/api/v1/.env:/app/v1/.env \
            ${{ secrets.DOCKERHUB_USERNAME }}/file-sharing-api:latest \
            /bin/bash -c "cd /app && pytest tests/"

      - name: Push API Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/}/file-sharing-api:latest
